server:
  port: 11110
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://billo.iptime.org:10002/studyjpa?serverTimezone=UTC&useSSL=true&requireSSL=false
    username: billo
    password: Tmdals2!
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 3000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security:
  oauth2:
    client:
      registration:
        google:
          client-id: # 발급 받은 client-id #
          client-secret: # 발급 받은 client-secret #
          scope: # 필요한 권한 #
        kakao:
          client-id: # 발급 받은 client-id #
          client-secret: # 발급 받은 client-secret #
          scope: # 필요한 권한 #
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          authorization-grant-type: authorization_code
          client-name: kakao
          client-authentication-method: POST
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id


jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJzdWIiOiIwMTA0MDA4Mjg4MiIsIm5hbWUiOiJjaG9zZXVuZ2hlZSIsImlhdCI6MTYyODg2NjgwMH0Sx241i49LSY6wUTxMjXIIaiDiIIROSNM9nipjPld86M
  token-validity-in-seconds: 86400 #토큰의 만료시간을 지정함.
